BookstoreWeb/Components/CategoriesMenuViewComponent.cs
using BookstoreWeb.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BookstoreWeb.Components
{
    // Класс навигационного компонента представления
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly ICategoryRepository repository;

        public CategoriesMenuViewComponent(ICategoryRepository repository) => this.repository = repository;

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Categories.OrderBy(x => x.Name));
        }
    }
}

BookstoreWeb/Controllers/CartController.cs
using BookstoreWeb.Models.Entities;
using BookstoreWeb.Models.Interfaces;
using BookstoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BookstoreWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly Cart cart;

        public CartController(IBookRepository bookRepository, Cart cart) => 
            (this.bookRepository, this.cart) = (bookRepository, cart);


        // Извлекает объект Cart из состояния сеанса и использует
        // его при создании объекта CartIndexViewModel, который затем передается методу
        // View() для применения в качестве модели представления.
        public ViewResult Index(string returnUrl) => View(new CartIndexViewModel
        {
            Cart = cart,
            ReturnUrl = returnUrl
        });

        public RedirectToActionResult AddToCart(long Id, string returnUrl)
        {
            Book book = bookRepository.Books.FirstOrDefault(b => b.Id == Id);

            if (book != null)
                cart.AddItem(book, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(long Id, string returnUrl)
        {
            Book book = bookRepository.Books.FirstOrDefault(b => b.Id == Id);

            if (book != null)
                cart.RemoveLine(book);

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

BookstoreWeb/Controllers/HomeController.cs
using BookstoreWeb.Models.Interfaces;
using BookstoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BookstoreWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly ICategoryRepository categoryRepository;
        public int PageSize = 12; // На каждой странице будет отображаться по 12 книг

        public HomeController(IBookRepository bookRepository, ICategoryRepository categoryRepository) =>
            (this.bookRepository, this.categoryRepository) = (bookRepository, categoryRepository);

        public ViewResult Index(string category, int bookPage = 1) => View(new BooksListViewModel
        {
            Categories = categoryRepository.Categories,

            Books = bookRepository.Books
                .Where(b => category == null || b.Category.Name == category)
                .OrderBy(b => b.Id)
                .Skip((bookPage - 1) * PageSize)
                .Take(PageSize),

            PagingInfo = new PagingInfo
            {
                CurrentPage = bookPage,
                ItemsPerPage = PageSize,
                TotalItems = category == null ? bookRepository.Books.Count() : bookRepository.Books.Where(e => e.Category.Name == category).Count()
            },

            CurrentCategory = category
        });

        public ViewResult BookDescription(int Id) => View(bookRepository.Books.FirstOrDefault(b => b.Id == Id));
    }
}

BookstoreWeb/Views/Home/BookDescription.cshtml
@model Book

@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/book.css">

<!-- Полная информация о книге для пользователя -->
<main>
    <!-- Основной блок с подробным описанием книги -->
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <!-- Картинка книги -->
            <div class="col-lg-3 col-sm-6">
                <img class="card-img-top" alt="book" src=@("data:image/jpeg;base64," + Convert.ToBase64String(Model.Image))>
            </div>

            <!-- Блок общих данных -->
            <div class="col-lg-6 col-sm-6">
                <h4 class="text-center book-title">@Model.Name</h4>
                <div class="row">
                    <!-- Колонка с таблицей -->
                    <div class="col-lg-9 col-sm-6">
                        <div class="description">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <th>Автор:</th>
                                        <td>@Model.Author</td>
                                    </tr>
                                    <tr>
                                        <th>ID товара:</th>
                                        <td>@Model.Id</td>
                                    </tr>
                                    <tr>
                                        <th>Издательство:</th>
                                        <td>@Model.Publisher</td>
                                    </tr>
                                    <tr>
                                        <th>Год издания:</th>
                                        <td>@Model.YearPublishing</td>
                                    </tr>
                                    <tr>
                                        <th>Количество страниц:</th>
                                        <td>@Model.PageCount</td>
                                    </tr>
                                    <tr>
                                        <th>Тираж:</th>
                                        <td>@Model.Circulation</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- Колонка с карточкой В корзину -->
                    <div class="col-lg-3">
                        <div class="row justify-content-center">
                            <div class="buy-block">
                                <div class="buy-block-style">
                                    <div class="block-text text-center">
                                        <span class="price">@Model.Price.ToString("c")</span>
                                        <div class="block-btn">
                                            <!-- Кнопка В корзину -->
                                            <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
                                                <input type="hidden" asp-for="Id" />
                                                <input type="hidden" name="returnUrl"
                                                       value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                <button type="submit" class="cart-btn">В корзину</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Аннотация -->
            <div class="row justify-content-center">
                <div class="col-lg-9 col-sm-12">
                    <div class="annotation-title">
                        <h5>Аннотация</h5>
                    </div>
                    <div class="annotation-text">@Model.Annotation</div>
                </div>
            </div>
        </div>
    </div>

</main>

BookstoreWeb/Views/Home/Index.cshtml
@model BooksListViewModel

<link rel="stylesheet" href="~/css/main.css">


<!-- Основной контент -->
<main>

    <!-- Секция с новостью -->
    <section id="home">
        <div class="block-news container-fluid" id="text">
            <h5 class="text-uppercase">Новое поступление</h5>
            <h1><span>Лучшие цены</span> этого года</h1>
            <p>Мы собрали самые популярные книги в одном месте.</p>
        </div>
    </section>

    <!-- Секция книг -->
    <section id="featured" class="my-5 pb-5">

        <!-- Заголовок -->
        <div class="container text-center mt-5 py-5">
            <h3>Каталог книг</h3>
            <hr class="mx-auto my-line">
            <p>Люди перестают мыслить, когда перестают читать.</p>
        </div>

        <!-- Сайдбар, карточки книг и страницы -->
        <div class="container block-books">
            <div class="row">

                <!-- Сайдбар с категориями книг -->
                <div class="col-lg-3 bg-light mt-5">
                    <aside>
                        <div class="side-content">
                            <div class="sidebar-title">Жанры</div>
                            <hr>

                            <!-- Сайдбар категорий -->
                            <!-- Применяем компонент представлений -->
                            <vc:categories-menu />

                            <hr>
                        </div>
                    </aside>
                </div>

                <!-- Карточки книг -->
                <div class="col-lg-9 mt-5">
                    <div class="row">

                        @foreach (var book in Model.Books)
                        {
                            <!-- Подключение частичного представления -->
                            <!-- Карточка книги -->
                            <partial name="BooksList" model="book" />
                        }

                        <!-- Страницы перехода по книгам -->
                        <div page-model="@Model.PagingInfo"
                             page-action="Index"
                             page-classes-enabled="true"
                             page-class-normal="btn-books-page"
                             page-class-selected="btn-books-page-active"
                             page-url-category="@Model.CurrentCategory"
                             class="page-block">
                        </div>

                    </div>
                </div>

            </div>
        </div>

    </section>

    <!-- Блок карусели с заставками -->
    <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">

        <!-- Горизонтальные линии перехода по слайдам -->
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>

        <div class="carousel-inner">
            <!-- Элемент карусели 1 -->
            <div class="carousel-item active" data-interval="50">
                <img src="~/img/slide/slide2.jpg" alt="slide">
                <div class="container my-carousel">
                    <div class="carousel-caption text-start">
                        <h1>Ликвидация отдела</h1>
                        <p>Заходите в наш старый отдел за бесплатными журналами</p>
                        <!-- Кнопка на картинке -->
                        <p><a class="btn btn-lg btn-carousel" href="#">Узнать больше</a></p>
                    </div>
                </div>
            </div>

            <!-- Элемент карусели 2 -->
            <div class="carousel-item" data-interval="50">
                <img src="~/img/slide/slide1.jpg" alt="slide">
                <div class="container my-carousel">
                    <div class="carousel-caption">
                        <h1>Читать - не перечитать</h1>
                        <p>Скидки на бестселлеры и новинки</p>
                        <!-- Кнопка на картинке -->
                        <p><a class="btn btn-lg btn-carousel" href="#">Узнать больше</a></p>
                    </div>
                </div>
            </div>

            <!-- Элемент карусели 3 -->
            <div class="carousel-item" data-interval="50">
                <img src="~/img/slide/slide3.jpg" alt="slide">
                <div class="container my-carousel">
                    <div class="carousel-caption text-end">
                        <h1>Барсик поможет выбрать книгу</h1>
                        <p>В нашем книжном завелся новый питомец</p>
                        <!-- Кнопка на картинке -->
                        <p><a class="btn btn-lg btn-carousel" href="#">Узнать больше</a></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Уголки-кнопки для перехода по слайдам -->
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

</main>