BookstoreWeb/Models/ViewModels/BooksListViewModel.cs
using BookstoreWeb.Models.Entities;
using System.Collections.Generic;

namespace BookstoreWeb.Models.ViewModels
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }

        public IEnumerable<Category> Categories { get; set; }

        public PagingInfo PagingInfo { get; set; }

        public string CurrentCategory { get; set; }
    }
}

BookstoreWeb/Components/CartSummaryViewComponent.cs
using BookstoreWeb.Models.Entities;
using Microsoft.AspNetCore.Mvc;

namespace BookstoreWeb.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;

        public CartSummaryViewComponent(Cart cartService) => cart = cartService;

        public IViewComponentResult Invoke() => View(cart);
    }
}

BookstoreWeb/Controllers/CartController.cs
using BookstoreWeb.Models.Entities;
using BookstoreWeb.Models.Interfaces;
using BookstoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BookstoreWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly Cart cart;

        public CartController(IBookRepository bookRepository, Cart cart) => 
            (this.bookRepository, this.cart) = (bookRepository, cart);


        // Извлекает объект Cart из состояния сеанса и использует
        // его при создании объекта CartIndexViewModel, который затем передается методу
        // View() для применения в качестве модели представления.
        public ViewResult Index(string returnUrl) => View(new CartIndexViewModel
        {
            Cart = cart,
            ReturnUrl = returnUrl
        });

        public RedirectToActionResult AddToCart(long Id, string returnUrl)
        {
            Book book = bookRepository.Books.FirstOrDefault(b => b.Id == Id);

            if (book != null)
                cart.AddItem(book, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(long Id, string returnUrl)
        {
            Book book = bookRepository.Books.FirstOrDefault(b => b.Id == Id);

            if (book != null)
                cart.RemoveLine(book);

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

BookstoreWeb/Views/Shared/BooksList.cshtml
 @model Book

<!-- Карточка книги -->
<div class="col-lg-3 col-sm-6">
    <div class="product text-center">
        @{
            string data = Convert.ToBase64String(Model.Image);
            string imgDataURL = string.Format("data:image/jpg;base64,{0}", data);
        }
        <img class="card-img-top" alt="book" src="@imgDataURL">
        <div class="card-body">
            @Model.Author <p class="card-title">@Model.Name</p>
            <h5 class="p-price">@Model.Price.ToString("c")</h5>
            <div style="flex-wrap: wrap;">

                <!-- Кнопка В корзину -->
                <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" name="returnUrl"
                           value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <button type="submit" class="buy-btn">В корзину</button>
                </form>

                <!-- Кнопка Подробней -->
                <a class="read-btn" asp-action="BookDescription" asp-route-Id="@Model.Id">Подробней</a>
            </div>
        </div>
    </div>
</div>

BookstoreWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <link rel="stylesheet" href="~/css/general.css">
    
    <link rel="icon" href="~/img/favicon.ico" type="image/x-icon">

    <title>Bookstore admin</title>
</head>

<body>

    <div class="wrapper">


        <!-- Header -->
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap py-1 shadow">

            <!-- Логотип бренда -->
            <div class="navbar-brand">
                <a href="/" class="to-site">
                    <img src="~/img/logo.png" alt="logo" class="logo-img">
                    Bookstore
                </a>
            </div>

            <!-- Кнопка меню для мобильной версии -->
            <button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span><i id="bar" class="fas fa-bars"></i></span>
            </button>

            <!-- Кнопка Выход -->
            @*<ul class="navbar-nav">
                <li class="nav-item text-nowrap">
                    <a class="out-btn" asp-action="Logout" asp-controller="Account">Выйти из аккаунта</a>
                </li>
            </ul>*@
        </header>

        <!-- Основной контент -->
        <div class="container-fluid">
            <div class="row">

                <!-- Сайдбар со списком вкладок -->
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="side">
                        <div class="position-sticky sidebar-style pt-3">
                            <ul class="nav flex-column">

                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-action="Index">
                                        <i class="fas fa-info-circle"></i>
                                        <span class="sidebar-text">Сервер</span>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" asp-action="OrdersList">
                                        <i class="fas fa-bags-shopping"></i>
                                        <span class="sidebar-text">Заказы</span>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" asp-action="BooksList">
                                        <i class="fas fa-books"></i>
                                        <span class="sidebar-text">Книги</span>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" asp-action="CategoriesList">
                                        <i class="fas fa-list-alt"></i>
                                        <span class="sidebar-text">Категории книг</span>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" asp-action="DatabaseControl">
                                        <i class="fas fa-database"></i>
                                        <span class="sidebar-text">Управление БД</span>
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </div>
                </nav>

                <!-- Основная часть -->
                @RenderBody()


            </div>
        </div>

    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
</body>

</html>

BookstoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <!-- CSS -->
    <link rel="stylesheet" href="~/css/general.css">
    <link rel="stylesheet" href="~/css/header.css">    
    <link rel="stylesheet" href="~/css/footer.css">

    <link rel="icon" href="~/img/favicon.ico" type="image/x-icon">

    <title>Bookstore</title>

</head>

<body>

    <div class="wrapper">

        <!-- Header -->
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3 fixed-top">
                <div class="container">

                    <!-- Логотип бренда -->
                    <div class="navbar-brand">
                        <img src="~/img/logo.png" alt="logo" class="logo-img">
                        <h6>Bookstore</h6>
                    </div>

                    <!-- Кнопка меню для мобильной версии -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#toggleMobileMenu" aria-controls="toggleMobileMenu" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span><i id="bar" class="fas fa-bars"></i></span>
                    </button>

                    <!-- Заголовки меню, которые сворачиваются в мобильной версии -->
                    <div class="collapse navbar-collapse justify-content-center" id="toggleMobileMenu">

                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/">Бестселлеры</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/">Блоги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="Admin">Администратор</a>
                            </li>
                        </ul>
                    </div>

                    <!-- Иконка корзины -->
                    <div class="collapse navbar-collapse justify-content-end" id="toggleMobileMenu">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <!-- Компонент представления. Иконка корзины и надпись -->
                                <vc:cart-summary />
                            </li>
                        </ul>
                    </div>

                </div>
            </nav>

        </header>

       @RenderBody()

        <!-- Footer -->
        <footer class="footer py-5 mt-auto">
            <div class="row container mx-auto pt-5">

                <!-- Колонка с логотипом -->
                <div class="footer-one col-lg-3 col-md-6 col-12">
                    <img class="pt-3 footer-logo" src="~/img/logo2.png" alt="logo">
                    <span class="pl-2 footer-text-logo">Bookstore</span>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe ea nostrum quae repellat porro
                        sint quia quibusdam ipsam!
                    </p>
                </div>

                <!-- Колонка ссылок-->
                <div class="footer-one col-lg-3 col-md-6 col-12 mb-3">
                    <h5>О магазине</h5>
                    <ul class="text-uppercase list-unstyled">
                        <li><a href="#">О нас</a></li>
                        <li><a href="#">Программа лояльности</a></li>
                        <li><a href="#">Акции и новости</a></li>
                        <li><a href="#">Фотогалерея</a></li>
                        <li><a href="#">Вакансии</a></li>
                        <li><a href="#">События</a></li>
                    </ul>
                </div>

                <!-- Колонка с информацией-->
                <div class="footer-one col-lg-3 col-md-6 col-12 mb-3">
                    <h5 class="pb-2">Свяжитесь с нами</h5>
                    <div>
                        <h6 class="text-uppercase">Адрес</h6>
                        <p>123 STREET NAME CITY, US</p>
                    </div>
                    <div>
                        <h6 class="text-uppercase">Телефон</h6>
                        <p>(900) 123-454-5470</p>
                    </div>
                    <div>
                        <h6 class="text-uppercase">Email</h6>
                        <p>mysite@email.com</p>
                    </div>
                </div>

                <!-- Колонка с инстаграмом -->
                <div class="footer-one col-lg-3 col-md-6 col-12">
                    <h5 class="pb-2">Instagram</h5>
                    <div class="row">
                        <img class="img-fluid w-25 h-100 m-2" src="~/img/instagram/inst1.jpg" alt="">
                        <img class="img-fluid w-25 h-100 m-2" src="~/img/instagram/inst2.jpg" alt="">
                        <img class="img-fluid w-25 h-100 m-2" src="~/img/instagram/inst3.jpg" alt="">
                        <img class="img-fluid w-25 h-100 m-2" src="~/img/instagram/inst4.jpg" alt="">
                        <img class="img-fluid w-25 h-100 m-2" src="~/img/instagram/inst5.jpg" alt="">
                    </div>
                </div>
            </div>

            <!-- Нижний текст с копирайтом и ссылками соцсетей -->
            <div class="copyright mt-5">
                <div class="row container mx-auto">
                    <div class="col-lg-3 col-md-6 col-12 mb-4">
                        <img class="img-fluid img-payment" src="~/img/payment.jpg" alt="">
                    </div>
                    <div class="col-lg-4 col-md-6 col-12 text-nowrap mb-2">
                        <p>© 2021 "Elizabeth-tech" Все права защищены</p>
                    </div>
                    <div class="col-lg-4 col-md-6 col-12">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>

        </footer>

    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>

</body>

</html>